[feat] 글씨 크기 조절
TUK-DP/frontend-v2 pull request #100
Opened 2024-07-26 14:20 UTC by Hj1218

## PR type
- [ ] Bug fix
- [ ] Feature
- [ ] Refactor
- [ ] Chore

## 💻 작업사항

- root 폰트사이즈 변경

![글씨 크기 조절](https://github.com/user-attachments/assets/37b37425-54ee-4619-af74-a68f4ac141c1)

## 💡 작성한 이슈 외에 작업한 사항

- 없음

## ✔️ check list

- [ ] 작성한 이슈의 내용을 전부 적용했나요?
- [ ] 리뷰어를 등록했나요?

2024-07-27 05:53 UTC, heedong12 approved these changes
👍

2024-07-27 06:01 UTC, Leewonchan14 requested changes
우리 전역 상태 관리 zustand 사용중인데 context api 말고 zustrand 로 바꿔주세요

src/stores 에 사용법들 있으니까 어렵지 않게 사용 가능합니다.

2024-07-27 06:01 UTC, Leewonchan14 commented on src/components/mypage/FontSizeControl.jsx
>    return (
onClick 인자로 `({title, size})` 자체를 넘겨주면 find 호출없이 setter 사용이 가능할것 같아요

2024-07-28 15:57 UTC, Hj1218 commented on src/components/mypage/FontSizeControl.jsx
>    return (
둘 다 수정했습니당

2024-07-29 02:18 UTC, Leewonchan14 approved these changes

2024-07-29 13:14 UTC, merged