Feat/86 일기 회상 문제 api 연동 + 문제 제출후 정답 확인 API 로직 까지 연동
TUK-DP/frontend-v2 pull request #111
Opened 2024-08-01 13:12 UTC by heedong12

## PR type
- [x] Feature

## 💻 작업사항

- 일기 회상 문제 api 연결
- 일기 회상 문제 제출 후 정답 확인 api 연결

## 💡 작성한 이슈 외에 작업한 사항

- 버튼 디자인 변경

## Image
<img src="https://github.com/user-attachments/assets/d4ac6038-b40e-40b8-86a5-8ae77a1f4ca2" width="300" />

## ✔️ check list

- [x] 작성한 이슈의 내용을 전부 적용했나요?
- [x] 리뷰어를 등록했나요?

2024-08-01 13:32 UTC, Leewonchan14 requested changes
만약 일기 수정중에 일기 회상 버튼을 누르면 어떻게 되는지 확인해 봤나요?

2024-08-01 13:32 UTC, Leewonchan14 commented on src/hooks/diary/queries/useFetchRecallQuiz.js
> +const useFetchDiaryRecallQuiz = (diaryId) => {
```suggestion
const useFetchDiaryRecallQuiz = () => {
  const { diary } = useFetchDiary();
  const { diaryId } = diary;
```

diaryId 지금 코드에서 가져올수 있으니까 수정해 주세요

2024-08-01 13:47 UTC, Leewonchan14 commented
키워드 없을때 키워드 없다는 페이지 연결 되어있어요?

<img width="300" alt="image" src="https://github.com/user-attachments/assets/96eb51fa-4ae2-4ad9-b365-b78113c77bb6">

요거

2024-08-01 15:23 UTC, Leewonchan14 commented
그리고 이제 PR 제목 label/issueNumber 로 작성해 주세요 (Feat/86) 처럼

2024-08-01 15:46 UTC, Hj1218 approved these changes

2024-08-01 18:25 UTC, heedong12 commented
> 만약 일기 수정중에 일기 회상 버튼을 누르면 어떻게 되는지 확인해 봤나요?

일기 회상 버튼이랑 일기 수정 버튼이랑 다른 페이지에 있지 않나요?

2024-08-01 18:25 UTC, heedong12 commented
> 키워드 없을때 키워드 없다는 페이지 연결 되어있어요?
> 
> <img alt="image" width="300" src="https://private-user-images.githubusercontent.com/105588857/354250111-96eb51fa-4ae2-4ad9-b365-b78113c77bb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MzU4OTEsIm5iZiI6MTcyMjUzNTU5MSwicGF0aCI6Ii8xMDU1ODg4NTcvMzU0MjUwMTExLTk2ZWI1MWZhLTRhZTItNGFkOS1iMzY1LWI3ODExM2M3N2JiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQxODA2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTQzMjM0MDU3ZTllOGJhZTY0OTliMGFmMDgwNzY5NDQwZmZkZjdjYzNjZDljODI1ZGJiNTdlYjU0OWY1OTYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JpD71qGy1PS9YJcmXDxYBZIHzFDVw7U1VCHIgk1guCI">
> 요거

연결완료했습니당

2024-08-02 04:17 UTC, Leewonchan14 approved these changes
현재 회상 정답을 제출했을때 답이 다 보이게끔 AnswerBox 가 다 열려 있는데 초기값을 다 닫는걸로 해주세요

2024-08-02 07:22 UTC, merged