Feat/112 useFetchDiaryRecallQuiz 의 diaryId 수정, 그림 로직에서 사용되는 keyword 모두 useFetchDiary에서 가져오기
TUK-DP/frontend-v2 pull request #115
Opened 2024-08-02 08:49 UTC by heedong12

## PR type
- [ ] Feature

## 💻 작업사항

- 키워드 정보 useFetchDiary에서 가져오도록 수정
- 선택된 키워드 정보 전역변수로 설정
- 키워드 없을 때, 기본 키워드로 설정

## 💡 작성한 이슈 외에 작업한 사항

- 치매진단 오류 해결
- userId를 useRequireAuth에서 가져오도록 수정

## Image
<img width="300" alt="image" src="https://github.com/user-attachments/assets/c88cd6f1-b116-425d-ac75-5d6d75020fe5">

## ✔️ check list

- [ ] 작성한 이슈의 내용을 전부 적용했나요?
- [ ] 리뷰어를 등록했나요?

2024-08-02 09:22 UTC, Leewonchan14 requested changes
전체적으로 `{userId : userId}` 로 넣은게 많은데 이쁘게 `{ userId }` 로 바꿔주세요

2024-08-02 09:22 UTC, Leewonchan14 commented on src/components/draw/CanvasWrapper.jsx
키워드는 useFetchKeyword 에서 가져오는거 아니였나요?

2024-08-02 09:22 UTC, Leewonchan14 commented on src/components/draw/KeywordSlider.jsx
> +            {keyword.keyword}
```javascript
keywords.map(({keyword, keywordId}) => (
  key={keywordId}
  keyword=keyword
)
```
는 어떨까요

2024-08-02 09:22 UTC, Leewonchan14 commented on src/hooks/canvas/useFetchKeyword.js
> +export default useFetchKeywords;
키워드가 없을때 "자유롭게 그려주세요!" 를 넣는다면
- 키워드 참조 그림
- AI 그림 도움받기 
쪽에서 어떻게 구현해야할까요...


useFetchKeywords 쪽에서 isKeywordsEmpty 같은 변수를 같이 return 하는건 어떨까요

2024-08-02 09:26 UTC, Leewonchan14 commented on src/components/draw/CanvasWrapper.jsx
전역으로 가져올수 keywords를 props 로 내려주지말고 useFetchKeywords로 직접 가져와 주세요

2024-08-02 09:27 UTC, Leewonchan14 commented on src/components/draw/CanvasWrapper.jsx
<img width="400" alt="image" src="https://github.com/user-attachments/assets/d0b8063d-f0f7-443b-b781-7a5b5f20c4f3">

위 DiaryDraw 컴포넌트에서는 keywords 가 필요없는데 내려주기 위해 호출하네요

2024-08-02 13:02 UTC, Hj1218 approved these changes

2024-08-03 11:39 UTC, Leewonchan14 approved these changes

2024-08-03 11:44 UTC, merged