[fix]isKeywordEmpty 변수 오류 해결
TUK-DP/frontend-v2 pull request #120
Opened 2024-08-03 12:46 UTC by heedong12

## PR type
- [ ] Bug fix

## 💻 작업사항

- isKeywordEmpty 변수 오류 해결

## 💡 작성한 이슈 외에 작업한 사항

- 없음

## Image
키워드 없을 때
<img width="164" alt="image" src="https://github.com/user-attachments/assets/292ef3de-53a2-4b70-adea-754cb7d408fd">
키워드 있을 때
<img width="190" alt="image" src="https://github.com/user-attachments/assets/b24d199c-577e-4d17-9b90-5d7f1dd87812">

## ✔️ check list

- [ ] 작성한 이슈의 내용을 전부 적용했나요?
- [ ] 리뷰어를 등록했나요?

2024-08-03 12:49 UTC, Hj1218 approved these changes

2024-08-04 02:07 UTC, Leewonchan14 requested changes

2024-08-04 02:07 UTC, Leewonchan14 commented on src/hooks/canvas/useFetchKeyword.js
> +
```javascript
const useFetchKeywords = () => {
  const { diary } = useFetchDiary();

  const isKeywordEmpty = !diary?.keywords?.length;

  let keywords = isKeywordEmpty
    ? [
        {
          keyword: "자유롭게 그려보세요!",
          keywordId: 0,
          imgUrl: null,
        },
      ]
    : diary.keywords;

  return { keywords, isKeywordEmpty };
};
```

2024-08-04 02:10 UTC, Leewonchan14 commented on src/hooks/canvas/useFetchKeyword.js
> +
const 로 변경하고

isKeywordsEmpty로 변수명 변경해 주세요

2024-08-04 03:41 UTC, Leewonchan14 approved these changes

2024-08-04 03:41 UTC, merged