Publishing/145 그리기 도구 수정
TUK-DP/frontend-v2 pull request #154
Opened 2024-08-10 10:00 UTC by Hj1218

## PR type
- [ ] Bug fix
- [ ] Feature
- [ ] Refactor
- [ ] Chore
- [ ] Publishing

## 💻 작업사항

- 내용에 맞춰 컬러피커 모달 height fit 조정
- 모달 뒷배경 스크롤 막기
- 모달 닫는 버튼 추가
- 도구팔레트 토글 반응형추가

## 💡 작성한 이슈 외에 작업한 사항

- 불필요한 코드 삭제

## ✔️ check list

- [ ] 작성한 이슈의 내용을 전부 적용했나요?
- [ ] 리뷰어를 등록했나요?

2024-08-10 10:48 UTC, heedong12 commented on src/components/draw/ColorPickerComp.js
> +          취소
취소 말고 그냥 X 표시로 두는 건 어떨까요..?

2024-08-10 10:50 UTC, heedong12 commented
색상 선택 슬라이더랑 투명도 조절 슬라이더 사이 간격 
색상 선택 부분과 아래 슬라이더 영역 분리(선 추가?)
이 부분도 추가해주실 수 있나여..??

2024-08-11 02:34 UTC, Leewonchan14 requested changes
사진 추가 해 주세용

2024-08-11 10:55 UTC, Hj1218 commented on src/components/draw/ColorPickerComp.js
> +          취소
수정할게용

2024-08-11 11:52 UTC, Hj1218 commented
@heedong12 @Leewonchan14  추가했습니다!

2024-08-12 02:56 UTC, Leewonchan14 approved these changes
직접 css를 만지는게 좀 아쉽긴 하네요

일단 굳 👍

2024-08-12 06:55 UTC, heedong12 approved these changes
👍

2024-08-12 07:20 UTC, merged