Publishing/34
TUK-DP/frontend-v2 pull request #38
Opened 2024-07-15 15:25 UTC by heedong12

## PR type
- [x] Publishing

## 💻 작업사항

- 일기회상 문제 있을 때 페이지 퍼블리싱
- 일기회상 문제 없을 때 페이지 퍼블리싱

## 💡 작성한 이슈 외에 작업한 사항

- tailwind 색상 추가
<img width="181" alt="image" src="https://github.com/user-attachments/assets/ab063f9d-1153-40a8-bfee-f4743e8fb673">
<img width="159" alt="image" src="https://github.com/user-attachments/assets/39e566f8-1814-4031-bc38-22c20b6ed970">

## 이미지
- 일기회상 문제 있을 때
모바일
<img width="216" alt="image" src="https://github.com/user-attachments/assets/873f021b-cb6f-4afa-83fd-c65359b04ad9">

테블릿
<img width="384" alt="image" src="https://github.com/user-attachments/assets/7f39b558-367d-41e4-b88b-0cf3e2812964">

- 일기회상 문제 없을 때
모바일
<img width="216" alt="image" src="https://github.com/user-attachments/assets/c9e26c61-573e-4a1d-811f-a0e6cff5f552">

테블릿
<img width="384" alt="image" src="https://github.com/user-attachments/assets/23ec58b7-9a78-44b5-a32f-ccaf393bdf79">

## ✔️ check list

- [x] 작성한 이슈의 내용을 전부 적용했나요?
- [x] 리뷰어를 등록했나요?

2024-07-15 15:28 UTC, Leewonchan14 approved these changes
💯

2024-07-16 03:13 UTC, Leewonchan14 requested changes
이거 빠르게 충돌 해결해 주세요

2024-07-16 04:27 UTC, Hj1218 commented on src/pages/NoDiaryRecall.jsx
> +};
공간이 넓은데 왼쪽에 치우친 느낌이라
태블릿 화면에 맞게 수정하는게 좋을 것 같아요

2024-07-16 04:27 UTC, Hj1218 commented on src/pages/DiaryRecall.jsx
> +        문제를 풀어보세요
'기억(일기내용)을 떠올려 빈칸에 알맞은 단어를 입력하세요'
이런식으로 수정하는게 좋을 것 같아용
적었던 단어라는 말이 어색해서 수정하는 게 좋을 것 같습니다

2024-07-17 23:09 UTC, Leewonchan14 approved these changes
👍

2024-07-18 04:40 UTC, Hj1218 commented
일기 회상 문제가 있을 때 태블릿화면에 맞춰서 전체적으로 크게 수정해주세용

2024-07-18 12:39 UTC, heedong12 commented
> 일기 회상 문제가 있을 때 태블릿화면에 맞춰서 전체적으로 크게 수정해주세용

수정했습니당

2024-07-18 12:58 UTC, Leewonchan14 reviewed
👍

2024-07-18 14:30 UTC, Hj1218 commented
![image](https://github.com/user-attachments/assets/7c0c1398-6c56-4de5-a3ce-ae214715b8e5)
이런식으로 꽉찼으면 좋겠어요
아직 너무 작습니당..

2024-07-18 14:51 UTC, Hj1218 approved these changes
좋습니당

2024-07-18 14:57 UTC, merged