Publishing/30 치매진단 페이지 퍼블리싱
TUK-DP/frontend-v2 pull request #44
Opened 2024-07-16 13:38 UTC by Hj1218

## PR type
- [ ] Bug fix
- [ ] Feature
- [ ] Refactor
- [ ] Chore
- [ ] Publishing

## 💻 작업사항

- 치매진단 페이지 퍼블리싱

![phone](https://github.com/user-attachments/assets/0eac0c91-24ab-4e35-901e-9dfad0b65302)

![ipad](https://github.com/user-attachments/assets/c0af5f23-e726-445d-8323-26dfe18eb417)

## 💡 작성한 이슈 외에 작업한 사항

- stepper 스크롤 가능하도록 구현
- 답을 체크한 경우만 체크아이콘으로 변경
- 슬라이드 이동에 맞춰 stepper 중앙으로 위치
- 마지막 슬라이더에서 완료를 눌렀을 때 체크하지 않은 문항이 존재하면 해당 문항으로 이동

## ✔️ check list

- [ ] 작성한 이슈의 내용을 전부 적용했나요?
- [ ] 리뷰어를 등록했나요?

2024-07-17 02:47 UTC, Leewonchan14 approved these changes
👍

2024-07-17 03:43 UTC, Leewonchan14 requested changes

2024-07-17 03:43 UTC, Leewonchan14 commented on src/components/diagnosis/Stepper.js
> +
- getSize 함수는 하드코딩도 많고 함수명이 헷갈리네요 밑에서 아이콘 사이즈를 얻는데 사용하는것 같은데 getIconSize가 어떤지?
- Icon의 크기를 width 로만 결정할수있는게 아니라 tailwind로도 가능할것 같은데 어떤가요?

2024-07-17 03:43 UTC, Leewonchan14 commented on src/components/diagnosis/Stepper.js
> +  }, [currentStep]);
가독성이 심하게 떨어지는거 같아요
early return 으로 가독성 향상 가능 할것 같아요

또한 useEffect의 동작 목표가 사용자가 버튼을 누르면 스텝바가 선택된 문항의 가운데 정렬로 보이는데
함수를 따로 빼서 쉽게 읽을수 있게 할수 있을것 같아요

currentStep 에 -1 을 왜하는지? 의문이네요

2024-07-17 03:43 UTC, Leewonchan14 commented on src/pages/dementiaDiagnosis/Diagnosis.js
> +  const totalSlides = 15;
## 예시
```javascript
export const RESPONSE_MANY_TIME = "자주 그렇다." // 예시
export const RESPONSE_SOMETIMES = "때때로 그렇다." // 예시
...
sliderItemList = [
  {
    id 또는 index : 0,
    stepIcon : ...
    selectedButton : null, 
    response : undefined.
  }, ...
]
```

> 위 코드는 예시로 한번에 상태를 관리하면 편할것 같아요

2024-07-17 03:43 UTC, Leewonchan14 commented on src/pages/dementiaDiagnosis/Diagnosis.js
> +  };
이것도 early return 으로 가독성 챙겨 주세요

2024-07-17 03:43 UTC, Leewonchan14 commented on src/pages/dementiaDiagnosis/Diagnosis.js
이 컴포넌트엔 자잘한 함수들이 많은것 같아요 useSlider({sliderRef}) 같이 커스텀 훅으로 빼면 가독성이 좋아 질것 같아요
```javascript
handlePrevClick,
handleNextClick,
handleSliderChange,
handleResponse???,
handleStepClick
등등
```

2024-07-17 03:43 UTC, Leewonchan14 commented on src/components/diagnosis/Stepper.js
> +          )}
간단하게 같은 파일에 컴포넌트 하나 만들어서 가독성 좋게 바꿀수 있을것 같아요

2024-07-17 11:13 UTC, heedong12 approved these changes
👍

2024-07-19 08:55 UTC, Hj1218 commented on src/components/diagnosis/Stepper.js
> +
tailwind로 변경하고 getsize 없앴습니당

2024-07-19 09:02 UTC, Hj1218 commented on src/pages/dementiaDiagnosis/Diagnosis.js
수정했습니당

2024-07-19 09:11 UTC, Hj1218 commented on src/components/diagnosis/Stepper.js
> +          )}
넵 수정하겠습니다

2024-07-19 09:17 UTC, Hj1218 commented on src/pages/dementiaDiagnosis/Diagnosis.js
> +  };
수정했습니당

2024-07-19 09:25 UTC, Hj1218 commented on src/components/diagnosis/Stepper.js
> +  }, [currentStep]);
함수 따로 빼고 가독성 좋게 수정했습니당
-1을 사용하지 않도록 수정했습니다

2024-07-19 10:06 UTC, Hj1218 commented on src/pages/dementiaDiagnosis/Diagnosis.js
> +  const totalSlides = 15;
상태관리하도록 변경했습니당

2024-07-19 11:59 UTC, Hj1218 commented
![image](https://github.com/user-attachments/assets/7d0b21f7-c080-4a45-92d2-cc533e72d095)

진행상태 나타내는 바도 추가했습니다

2024-07-20 03:16 UTC, Leewonchan14 approved these changes
👍

2024-07-20 10:31 UTC, merged